### ISSUE TITLE
REQ-017: Wrong Questions Statistics

### ISSUE THREAD

**Issue by gfdfranco** [TheCodingForceUPSLP/marathon-quiz-game#18]
# Wrong Questions Statistics

## Description
Implement system to track and store statistics about wrong answers for each question.

### File Format
```
id|question|opt1|opt2|opt3|correct|category|wrongCount
1|Question1|A|B|C|2|1|45
```

### Core Features
* Update questions.txt structure to include wrong answer counter
* Save and load wrong answer statistics
* Track most failed questions

### Tasks
1. File Operations
   - [ ] Modify file read function to handle wrongCount
   - [ ] Update file write function to save wrongCount
   - [ ] Handle backwards compatibility
   - [ ] Validate counter data during load

2. Wrong Answer Tracking
   - [ ] Increment counter when answer is wrong
   - [ ] Save updated counter to file
   - [ ] Handle counter overflow

### Integration Points
* Questions.txt file operations
* Game wrong answer detection
* Statistics display system
