### ISSUE TITLE
REQ-018: Difficult Questions Ranking

### ISSUE THREAD

**Issue by gfdfranco** [TheCodingForceUPSLP/marathon-quiz-game#19]
# Difficult Questions Ranking

## Description
Display top 5 most failed questions with their failure percentage and category information.

### Display Format
```
==============================
MOST CHALLENGING QUESTIONS
==============================
1. [ID: 5] - Failed 85% times
   Category: History
   
2. [ID: 12] - Failed 78% times
   Category: Science
   
[...]
==============================
```

### Core Features
* Display top 5 most failed questions
* Show failure percentage
* Group by category

### Tasks
1. Question Statistics Processing
   - [ ] Create function to calculate failure percentage
   - [ ] Sort questions by failure rate
   - [ ] Get top 5 most failed

2. Display System
   - [ ] Format display header
   - [ ] Show question ID and fail rate
   - [ ] Include category information
   - [ ] Format percentage display

**Comment by R1K4-13** [comment]
Hacer txt con preguntas a forma de ejemplo y además con las respuestas

top 5 de las preguntas más falladas

número de veces que se erran por preguntas
