### ISSUE TITLE
Add E13A Group Credits to Main Menu

### ISSUE THREAD

**Issue by gfdfranco** [TheCodingForceUPSLP/marathon-quiz-game#21]
# Add E13A Group Credits to Main Menu

## Description
Add a new option in the main menu to display the program credits, showing information about the E13A group and developers.

## Menu Update
```
============================
    MARATHON QUIZ GAME
============================
1. Register new question
2. Play game
3. Show credits
4. Exit

Select an option: _
```

## Credits Display Format
```
============================
    PROGRAM CREDITS
============================
Marathon Quiz Game
Developed by E13A Group

Team Members:
- STAFF [Ramírez Velázquez Daniel]
- TEAM LEADER [Name]
[Add other team members]

Universidad Politécnica de San Luis Potosí
Programming Languages Course
2024
============================
Press Enter to continue...
```

## Tasks
- [x] Add new menu option
- [x] Create credits display function
- [x] Update main loop to handle new option
- [x] Add proper formatting for credits screen
- [x] Add pause after displaying credits

## Technical Details
* Function name: `void displayCredits()`
* Clear screen before showing credits
* Wait for user input before returning to menu
* Use proper formatting and spacing

## Acceptance Criteria
- [x] New menu option works
- [x] Credits display correctly
- [x] Format is clear and readable
- [x] Returns to menu properly
- [x] No memory leaks
