### ISSUE TITLE
Refactor Main Menu Into Return Function

### ISSUE THREAD

**Issue by gfdfranco** [TheCodingForceUPSLP/marathon-quiz-game#22]
# Refactor Main Menu Into Return Function

## Description
Refactor the main menu into a separate function that returns the selected option, improving code organization and maintainability.

## Current Code
```c
// Currently in main():
while (1) {
    printf("\nMarathon Quiz Game\n");
    printf("1. Register new question\n");
    printf("2. Play game\n");
    printf("3. Show credits\n");
    printf("4. Exit\n");
    printf("Enter your choice: ");
    scanf("%d", &choice);
    getchar();
    // ...
}
```

## Required Function
```c
int displayMenu() {
    int choice;
    printf("\n============================\n");
    printf("    MARATHON QUIZ GAME\n");
    printf("============================\n");
    printf("1. Register new question\n");
    printf("2. Play game\n");
    printf("3. Show credits\n");
    printf("4. Exit\n");
    printf("============================\n");
    printf("Select an option: ");
    scanf("%d", &choice);
    getchar(); // Clear buffer
    
    return choice;
}
```

## Tasks
- [x] Create displayMenu() function
- [x] Add input validation in function
- [x] Update main() to use new function
- [ ] Ensure proper buffer clearing
- [x] Test all menu options

## Updated Main Usage
```c
int main() {
    Question* head = NULL;
    int choice;

    while (1) {
        choice = displayMenu();
        switch (choice) {
            // ... case handling
        }
    }
}
```

## Technical Details
* Function should be in separate header
* Return type: int
* Input validation included
* Clear screen before showing menu
* Handle invalid inputs

## Acceptance Criteria
- [x] Function returns correct option
- [x] Input validation works
- [x] Buffer clearing prevents issues
- [x] Menu displays correctly
- [x] Integration with main loop works
- [x] Error handling for invalid input
